name: Auto Deploy Backend to Render

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK }}
